-- DESC 테이블명
-- 테이블의 구조를 보여주는 명령어
-- NUMBER : 정수, 실수를 표기하는 자료형
-- NUMBER(4) : 4는 숫자 4자리
-- NUMBER(7,2) : 7은 정수 자리 수 7자리, 2는 소수 자리 수 2자리
-- VARCHAR2 : 문자열을 표기하는 자료형
-- UTF8 설정 : 영어 1Byte, 한글 3Byte
-- KSC5601 : 영어 1Byte, 한글 2Byte
-- VARCHAR2(10) : 10=자리수를 의미함
-- DATE : 날짜를 표기하는 자료형
DESC EMP;